# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d3037522b5c7adfc7ec4600e11443bafa6559a4fdb7671f6b226e4366846567e99f2afbfa76640d61a318c26a7df46bbdb4ed2ac4f9cb4253d57acfd88bea78
  ifttt_channel_key: <%= ENV["IFTTT_CHANNEL_KEY"] %>

test:
  secret_key_base: 5e630052441fc9caccf2706dbeb2dbb56c6fb626033260190f0d29bfad3c84bb56f5127c7d1d71e4ded16c78f0953e9f7f00fe372e21cd9a85b19dc9fd95b16f
  ifttt_channel_key: <%= ENV["IFTTT_CHANNEL_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ifttt_channel_key: <%= ENV["IFTTT_CHANNEL_KEY"] %>

